// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const challengeOwner = `-- name: ChallengeOwner :one
SELECT owner_id FROM public.owner_login_challenges WHERE digest=$1
`

func (q *Queries) ChallengeOwner(ctx context.Context, digest []byte) (int64, error) {
	row := q.db.QueryRow(ctx, challengeOwner, digest)
	var owner_id int64
	err := row.Scan(&owner_id)
	return owner_id, err
}

const consumeChallenge = `-- name: ConsumeChallenge :exec
UPDATE public.owner_login_challenges SET consumed_at=$2 WHERE digest=$1
`

type ConsumeChallengeParams struct {
	Digest     []byte
	ConsumedAt pgtype.Timestamptz
}

func (q *Queries) ConsumeChallenge(ctx context.Context, arg ConsumeChallengeParams) error {
	_, err := q.db.Exec(ctx, consumeChallenge, arg.Digest, arg.ConsumedAt)
	return err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :execrows
DELETE FROM public.owner_recovery_codes WHERE owner_id=$1 AND digest=$2
`

type ConsumeRecoveryCodeParams struct {
	OwnerID int64
	Digest  []byte
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRecoveryCode, arg.OwnerID, arg.Digest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeTOTP = `-- name: ConsumeTOTP :exec
UPDATE public.owners SET last_totp_counter=$2 WHERE id=$1
`

type ConsumeTOTPParams struct {
	ID              int64
	LastTotpCounter int64
}

func (q *Queries) ConsumeTOTP(ctx context.Context, arg ConsumeTOTPParams) error {
	_, err := q.db.Exec(ctx, consumeTOTP, arg.ID, arg.LastTotpCounter)
	return err
}

const createChallenge = `-- name: CreateChallenge :exec
INSERT INTO public.owner_login_challenges (digest,owner_id,auth_version,expires_at) VALUES ($1,$2,$3,clock_timestamp()+interval '5 minutes')
`

type CreateChallengeParams struct {
	Digest      []byte
	OwnerID     int64
	AuthVersion int64
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) error {
	_, err := q.db.Exec(ctx, createChallenge, arg.Digest, arg.OwnerID, arg.AuthVersion)
	return err
}

const createOwner = `-- name: CreateOwner :one
INSERT INTO public.owners (shop_id,email,password_hash) VALUES ($1,$2,$3) RETURNING id
`

type CreateOwnerParams struct {
	ShopID       int64
	Email        string
	PasswordHash string
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOwner, arg.ShopID, arg.Email, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO public.owner_sessions (digest,owner_id,auth_version,created_at,last_seen_at,expires_at) VALUES ($1,$2,$3,$4::timestamptz,$4::timestamptz,$4::timestamptz+interval '8 hours')
`

type CreateSessionParams struct {
	Digest      []byte
	OwnerID     int64
	AuthVersion int64
	IssuedAt    pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.Digest,
		arg.OwnerID,
		arg.AuthVersion,
		arg.IssuedAt,
	)
	return err
}

const createSetupShop = `-- name: CreateSetupShop :one
INSERT INTO public.shops (name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateSetupShop(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, createSetupShop, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const databaseTime = `-- name: DatabaseTime :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) DatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteChallenge = `-- name: DeleteChallenge :exec
DELETE FROM public.owner_login_challenges WHERE digest = $1
`

func (q *Queries) DeleteChallenge(ctx context.Context, digest []byte) error {
	_, err := q.db.Exec(ctx, deleteChallenge, digest)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM public.owner_sessions WHERE digest=$1
`

func (q *Queries) DeleteSession(ctx context.Context, digest []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, digest)
	return err
}

const enableMFA = `-- name: EnableMFA :exec
UPDATE public.owners SET mfa_enabled=true,last_totp_counter=$2 WHERE id=$1
`

type EnableMFAParams struct {
	ID              int64
	LastTotpCounter int64
}

func (q *Queries) EnableMFA(ctx context.Context, arg EnableMFAParams) error {
	_, err := q.db.Exec(ctx, enableMFA, arg.ID, arg.LastTotpCounter)
	return err
}

const failChallenge = `-- name: FailChallenge :exec
UPDATE public.owner_login_challenges SET attempts=attempts+1 WHERE digest=$1
`

func (q *Queries) FailChallenge(ctx context.Context, digest []byte) error {
	_, err := q.db.Exec(ctx, failChallenge, digest)
	return err
}

const lockChallenge = `-- name: LockChallenge :one
SELECT consumed_at IS NULL AND attempts<5 AND expires_at>clock_timestamp() AND auth_version=$2 AND purpose='login' AS usable FROM public.owner_login_challenges WHERE digest=$1 FOR UPDATE
`

type LockChallengeParams struct {
	Digest      []byte
	AuthVersion int64
}

func (q *Queries) LockChallenge(ctx context.Context, arg LockChallengeParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, lockChallenge, arg.Digest, arg.AuthVersion)
	var usable pgtype.Bool
	err := row.Scan(&usable)
	return usable, err
}

const lockEnrollment = `-- name: LockEnrollment :one
SELECT mfa_ciphertext,mfa_enabled FROM public.owners WHERE id=$1 FOR UPDATE
`

type LockEnrollmentRow struct {
	MfaCiphertext []byte
	MfaEnabled    bool
}

func (q *Queries) LockEnrollment(ctx context.Context, id int64) (LockEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, lockEnrollment, id)
	var i LockEnrollmentRow
	err := row.Scan(&i.MfaCiphertext, &i.MfaEnabled)
	return i, err
}

const lockFactor = `-- name: LockFactor :one
SELECT mfa_ciphertext,mfa_enabled,last_totp_counter,auth_version FROM public.owners WHERE id=$1 FOR UPDATE
`

type LockFactorRow struct {
	MfaCiphertext   []byte
	MfaEnabled      bool
	LastTotpCounter int64
	AuthVersion     int64
}

func (q *Queries) LockFactor(ctx context.Context, id int64) (LockFactorRow, error) {
	row := q.db.QueryRow(ctx, lockFactor, id)
	var i LockFactorRow
	err := row.Scan(
		&i.MfaCiphertext,
		&i.MfaEnabled,
		&i.LastTotpCounter,
		&i.AuthVersion,
	)
	return i, err
}

const lockOwnerSetup = `-- name: LockOwnerSetup :exec
LOCK TABLE public.owners IN EXCLUSIVE MODE
`

func (q *Queries) LockOwnerSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockOwnerSetup)
	return err
}

const lockPassword = `-- name: LockPassword :one
SELECT password_hash,auth_version,mfa_enabled FROM public.owners WHERE id=$1 FOR UPDATE
`

type LockPasswordRow struct {
	PasswordHash string
	AuthVersion  int64
	MfaEnabled   bool
}

func (q *Queries) LockPassword(ctx context.Context, id int64) (LockPasswordRow, error) {
	row := q.db.QueryRow(ctx, lockPassword, id)
	var i LockPasswordRow
	err := row.Scan(&i.PasswordHash, &i.AuthVersion, &i.MfaEnabled)
	return i, err
}

const ownerByEmail = `-- name: OwnerByEmail :one
SELECT id,password_hash,mfa_enabled,auth_version FROM public.owners WHERE email=$1
`

type OwnerByEmailRow struct {
	ID           int64
	PasswordHash string
	MfaEnabled   bool
	AuthVersion  int64
}

func (q *Queries) OwnerByEmail(ctx context.Context, email string) (OwnerByEmailRow, error) {
	row := q.db.QueryRow(ctx, ownerByEmail, email)
	var i OwnerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.AuthVersion,
	)
	return i, err
}

const ownerCount = `-- name: OwnerCount :one
SELECT count(*) FROM public.owners
`

func (q *Queries) OwnerCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, ownerCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pendingOwnerByEmail = `-- name: PendingOwnerByEmail :one
SELECT id,password_hash,mfa_ciphertext,mfa_enabled FROM public.owners WHERE email=$1
`

type PendingOwnerByEmailRow struct {
	ID            int64
	PasswordHash  string
	MfaCiphertext []byte
	MfaEnabled    bool
}

func (q *Queries) PendingOwnerByEmail(ctx context.Context, email string) (PendingOwnerByEmailRow, error) {
	row := q.db.QueryRow(ctx, pendingOwnerByEmail, email)
	var i PendingOwnerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.MfaCiphertext,
		&i.MfaEnabled,
	)
	return i, err
}

const saveMFASeed = `-- name: SaveMFASeed :exec
UPDATE public.owners SET mfa_ciphertext=$2 WHERE id=$1
`

type SaveMFASeedParams struct {
	ID            int64
	MfaCiphertext []byte
}

func (q *Queries) SaveMFASeed(ctx context.Context, arg SaveMFASeedParams) error {
	_, err := q.db.Exec(ctx, saveMFASeed, arg.ID, arg.MfaCiphertext)
	return err
}

const saveRecoveryCode = `-- name: SaveRecoveryCode :exec
INSERT INTO public.owner_recovery_codes (owner_id,digest) VALUES ($1,$2)
`

type SaveRecoveryCodeParams struct {
	OwnerID int64
	Digest  []byte
}

func (q *Queries) SaveRecoveryCode(ctx context.Context, arg SaveRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, saveRecoveryCode, arg.OwnerID, arg.Digest)
	return err
}

const takeAuthAttempt = `-- name: TakeAuthAttempt :one
INSERT INTO public.owner_auth_limits (bucket,window_start,attempts)
VALUES ($1,clock_timestamp(),1)
ON CONFLICT (bucket) DO UPDATE SET
 attempts=CASE WHEN owner_auth_limits.window_start <= clock_timestamp()-interval '15 minutes' THEN 1 ELSE LEAST(owner_auth_limits.attempts+1,1000) END,
 window_start=CASE WHEN owner_auth_limits.window_start <= clock_timestamp()-interval '15 minutes' THEN clock_timestamp() ELSE owner_auth_limits.window_start END
RETURNING attempts
`

func (q *Queries) TakeAuthAttempt(ctx context.Context, bucket []byte) (int32, error) {
	row := q.db.QueryRow(ctx, takeAuthAttempt, bucket)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const touchSession = `-- name: TouchSession :one
UPDATE public.owner_sessions AS session SET last_seen_at=clock_timestamp()
 FROM public.owners AS owner WHERE session.digest=$1 AND owner.id=session.owner_id
 AND owner.mfa_enabled AND owner.auth_version=session.auth_version
 AND session.expires_at>clock_timestamp() AND session.last_seen_at>clock_timestamp()-interval '30 minutes'
 RETURNING session.owner_id
`

func (q *Queries) TouchSession(ctx context.Context, digest []byte) (int64, error) {
	row := q.db.QueryRow(ctx, touchSession, digest)
	var owner_id int64
	err := row.Scan(&owner_id)
	return owner_id, err
}
