// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Owner struct {
	ID                         int64
	ShopID                     int64
	Email                      string
	PasswordHash               string
	MfaCiphertext              []byte
	MfaEnabled                 bool
	LastTotpCounter            int64
	AuthVersion                int64
	CreatedAt                  pgtype.Timestamptz
	MfaEnrollmentSessionDigest []byte
	MfaEnrollmentExpiresAt     pgtype.Timestamptz
}

type OwnerAuthLimit struct {
	Bucket      []byte
	WindowStart pgtype.Timestamptz
	Attempts    int32
}

type OwnerLoginChallenge struct {
	Digest      []byte
	OwnerID     int64
	AuthVersion int64
	Purpose     string
	ExpiresAt   pgtype.Timestamptz
	Attempts    int32
	ConsumedAt  pgtype.Timestamptz
}

type OwnerRecoveryCode struct {
	OwnerID int64
	Digest  []byte
}

type OwnerSession struct {
	Digest      []byte
	OwnerID     int64
	AuthVersion int64
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type Shop struct {
	ID           int64
	Name         string
	CurrencyCode string
	CountryCode  string
	Timezone     string
	CreatedAt    pgtype.Timestamptz
}
