// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMakerVariant = `-- name: AddMakerVariant :one
INSERT INTO public.product_variants(product_id,label,label_key,size_label,colour_pair,price_pence,supply_mode,stock_quantity)
VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id
`

type AddMakerVariantParams struct {
	ProductID     int64
	Label         string
	LabelKey      string
	SizeLabel     string
	ColourPair    string
	PricePence    pgtype.Int8
	SupplyMode    string
	StockQuantity int64
}

func (q *Queries) AddMakerVariant(ctx context.Context, arg AddMakerVariantParams) (int64, error) {
	row := q.db.QueryRow(ctx, addMakerVariant,
		arg.ProductID,
		arg.Label,
		arg.LabelKey,
		arg.SizeLabel,
		arg.ColourPair,
		arg.PricePence,
		arg.SupplyMode,
		arg.StockQuantity,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const advancePublicationRevision = `-- name: AdvancePublicationRevision :one
UPDATE public.products p SET revision=p.revision+1
FROM public.owners o WHERE o.shop_id=p.shop_id AND o.id=$1 AND p.id=$2 AND p.revision=$3
RETURNING p.revision
`

type AdvancePublicationRevisionParams struct {
	ID       int64
	ID_2     int64
	Revision int64
}

func (q *Queries) AdvancePublicationRevision(ctx context.Context, arg AdvancePublicationRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, advancePublicationRevision, arg.ID, arg.ID_2, arg.Revision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO public.products(shop_id,name,description,price_pence,certificate_name,creation_key,creation_hash)
SELECT o.shop_id,$2,$3,$4,$5,$6,$7 FROM public.owners o JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
RETURNING id,name,description,price_pence,certificate_name,revision
`

type CreateProductParams struct {
	Digest          []byte
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	CreationKey     string
	CreationHash    []byte
}

type CreateProductRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Digest,
		arg.Name,
		arg.Description,
		arg.PricePence,
		arg.CertificateName,
		arg.CreationKey,
		arg.CreationHash,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePence,
		&i.CertificateName,
		&i.Revision,
	)
	return i, err
}

const findCreation = `-- name: FindCreation :one
SELECT p.id,p.creation_hash FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id
WHERE o.id=$1 AND p.creation_key=$2
`

type FindCreationParams struct {
	ID          int64
	CreationKey string
}

type FindCreationRow struct {
	ID           int64
	CreationHash []byte
}

func (q *Queries) FindCreation(ctx context.Context, arg FindCreationParams) (FindCreationRow, error) {
	row := q.db.QueryRow(ctx, findCreation, arg.ID, arg.CreationKey)
	var i FindCreationRow
	err := row.Scan(&i.ID, &i.CreationHash)
	return i, err
}

const listMakerVariants = `-- name: ListMakerVariants :many
SELECT v.id,v.label,v.size_label,v.colour_pair,v.price_pence,v.supply_mode,v.stock_quantity
FROM public.product_variants v JOIN public.products p ON p.id=v.product_id JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
ORDER BY v.id LIMIT 51
`

type ListMakerVariantsParams struct {
	Digest []byte
	ID     int64
}

type ListMakerVariantsRow struct {
	ID            int64
	Label         string
	SizeLabel     string
	ColourPair    string
	PricePence    pgtype.Int8
	SupplyMode    string
	StockQuantity int64
}

func (q *Queries) ListMakerVariants(ctx context.Context, arg ListMakerVariantsParams) ([]ListMakerVariantsRow, error) {
	rows, err := q.db.Query(ctx, listMakerVariants, arg.Digest, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMakerVariantsRow
	for rows.Next() {
		var i ListMakerVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.SizeLabel,
			&i.ColourPair,
			&i.PricePence,
			&i.SupplyMode,
			&i.StockQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id,p.name,p.description,p.price_pence,p.certificate_name,p.revision
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
AND p.id>$2 ORDER BY p.id LIMIT 51
`

type ListProductsParams struct {
	Digest  []byte
	AfterID int64
}

type ListProductsRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Digest, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PricePence,
			&i.CertificateName,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicProduct = `-- name: PublicProduct :one
SELECT pp.snapshot,p.made_to_order_fallback FROM public.product_publications pp JOIN public.products p ON p.id=pp.product_id JOIN public.shop_publications sp ON sp.shop_id=p.shop_id
WHERE sp.public_key=$1 AND p.id=$2
`

type PublicProductParams struct {
	PublicKey string
	ID        int64
}

type PublicProductRow struct {
	Snapshot            []byte
	MadeToOrderFallback bool
}

func (q *Queries) PublicProduct(ctx context.Context, arg PublicProductParams) (PublicProductRow, error) {
	row := q.db.QueryRow(ctx, publicProduct, arg.PublicKey, arg.ID)
	var i PublicProductRow
	err := row.Scan(&i.Snapshot, &i.MadeToOrderFallback)
	return i, err
}

const publicProducts = `-- name: PublicProducts :many
SELECT pp.snapshot,p.id FROM public.product_publications pp JOIN public.products p ON p.id=pp.product_id JOIN public.shop_publications sp ON sp.shop_id=p.shop_id
WHERE sp.public_key=$1 AND p.id>$2 ORDER BY p.id LIMIT 51
`

type PublicProductsParams struct {
	PublicKey string
	AfterID   int64
}

type PublicProductsRow struct {
	Snapshot []byte
	ID       int64
}

func (q *Queries) PublicProducts(ctx context.Context, arg PublicProductsParams) ([]PublicProductsRow, error) {
	rows, err := q.db.Query(ctx, publicProducts, arg.PublicKey, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicProductsRow
	for rows.Next() {
		var i PublicProductsRow
		if err := rows.Scan(&i.Snapshot, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicShop = `-- name: PublicShop :one
SELECT sp.name,sp.tagline,sp.description FROM public.shop_publications sp
WHERE sp.public_key=$1 AND EXISTS(SELECT 1 FROM public.products p JOIN public.product_publications pp ON pp.product_id=p.id WHERE p.shop_id=sp.shop_id)
`

type PublicShopRow struct {
	Name        string
	Tagline     string
	Description string
}

func (q *Queries) PublicShop(ctx context.Context, publicKey string) (PublicShopRow, error) {
	row := q.db.QueryRow(ctx, publicShop, publicKey)
	var i PublicShopRow
	err := row.Scan(&i.Name, &i.Tagline, &i.Description)
	return i, err
}

const publicVariantStock = `-- name: PublicVariantStock :many
SELECT v.id,v.supply_mode,v.stock_quantity FROM public.product_variants v JOIN public.products p ON p.id=v.product_id JOIN public.product_publications pp ON pp.product_id=p.id JOIN public.shop_publications sp ON sp.shop_id=p.shop_id
WHERE sp.public_key=$1 AND p.id=$2 ORDER BY v.id LIMIT 51
`

type PublicVariantStockParams struct {
	PublicKey string
	ID        int64
}

type PublicVariantStockRow struct {
	ID            int64
	SupplyMode    string
	StockQuantity int64
}

func (q *Queries) PublicVariantStock(ctx context.Context, arg PublicVariantStockParams) ([]PublicVariantStockRow, error) {
	rows, err := q.db.Query(ctx, publicVariantStock, arg.PublicKey, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicVariantStockRow
	for rows.Next() {
		var i PublicVariantStockRow
		if err := rows.Scan(&i.ID, &i.SupplyMode, &i.StockQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishProduct = `-- name: PublishProduct :exec
INSERT INTO public.product_publications(product_id,revision,snapshot) VALUES($1,$2,$3)
ON CONFLICT(product_id) DO UPDATE SET revision=excluded.revision,snapshot=excluded.snapshot
`

type PublishProductParams struct {
	ProductID int64
	Revision  int64
	Snapshot  []byte
}

func (q *Queries) PublishProduct(ctx context.Context, arg PublishProductParams) error {
	_, err := q.db.Exec(ctx, publishProduct, arg.ProductID, arg.Revision, arg.Snapshot)
	return err
}

const publishShop = `-- name: PublishShop :one
INSERT INTO public.shop_publications(shop_id,public_key,name,tagline,description)
SELECT sh.id,$2,sh.name,sh.tagline,sh.description FROM public.shops sh JOIN public.owners o ON o.shop_id=sh.id WHERE o.id=$1
ON CONFLICT(shop_id) DO UPDATE SET name=excluded.name,tagline=excluded.tagline,description=excluded.description
RETURNING public_key
`

type PublishShopParams struct {
	ID        int64
	PublicKey string
}

func (q *Queries) PublishShop(ctx context.Context, arg PublishShopParams) (string, error) {
	row := q.db.QueryRow(ctx, publishShop, arg.ID, arg.PublicKey)
	var public_key string
	err := row.Scan(&public_key)
	return public_key, err
}

const readMakerProduct = `-- name: ReadMakerProduct :one
SELECT p.id,p.name,p.price_pence,p.revision,p.made_to_order_fallback
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadMakerProductParams struct {
	Digest []byte
	ID     int64
}

type ReadMakerProductRow struct {
	ID                  int64
	Name                string
	PricePence          int64
	Revision            int64
	MadeToOrderFallback bool
}

func (q *Queries) ReadMakerProduct(ctx context.Context, arg ReadMakerProductParams) (ReadMakerProductRow, error) {
	row := q.db.QueryRow(ctx, readMakerProduct, arg.Digest, arg.ID)
	var i ReadMakerProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PricePence,
		&i.Revision,
		&i.MadeToOrderFallback,
	)
	return i, err
}

const readProduct = `-- name: ReadProduct :one
SELECT p.id,p.name,p.description,p.price_pence,p.certificate_name,p.revision
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadProductParams struct {
	Digest []byte
	ID     int64
}

type ReadProductRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) ReadProduct(ctx context.Context, arg ReadProductParams) (ReadProductRow, error) {
	row := q.db.QueryRow(ctx, readProduct, arg.Digest, arg.ID)
	var i ReadProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePence,
		&i.CertificateName,
		&i.Revision,
	)
	return i, err
}

const readPublication = `-- name: ReadPublication :one
SELECT p.revision,COALESCE(pp.revision,0)::bigint AS published_revision,COALESCE(sp.public_key,'')::text AS public_key,sh.name AS shop_name,sh.tagline AS shop_tagline,sh.description AS shop_description,sh.revision AS shop_revision
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
JOIN public.shops sh ON sh.id=p.shop_id LEFT JOIN public.product_publications pp ON pp.product_id=p.id LEFT JOIN public.shop_publications sp ON sp.shop_id=p.shop_id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadPublicationParams struct {
	Digest []byte
	ID     int64
}

type ReadPublicationRow struct {
	Revision          int64
	PublishedRevision int64
	PublicKey         string
	ShopName          string
	ShopTagline       string
	ShopDescription   string
	ShopRevision      int64
}

func (q *Queries) ReadPublication(ctx context.Context, arg ReadPublicationParams) (ReadPublicationRow, error) {
	row := q.db.QueryRow(ctx, readPublication, arg.Digest, arg.ID)
	var i ReadPublicationRow
	err := row.Scan(
		&i.Revision,
		&i.PublishedRevision,
		&i.PublicKey,
		&i.ShopName,
		&i.ShopTagline,
		&i.ShopDescription,
		&i.ShopRevision,
	)
	return i, err
}

const recordStockAdjustment = `-- name: RecordStockAdjustment :exec
INSERT INTO public.stock_adjustments(variant_id,owner_id,previous_quantity,new_quantity,reason) VALUES($1,$2,$3,$4,$5)
`

type RecordStockAdjustmentParams struct {
	VariantID        int64
	OwnerID          int64
	PreviousQuantity int64
	NewQuantity      int64
	Reason           string
}

func (q *Queries) RecordStockAdjustment(ctx context.Context, arg RecordStockAdjustmentParams) error {
	_, err := q.db.Exec(ctx, recordStockAdjustment,
		arg.VariantID,
		arg.OwnerID,
		arg.PreviousQuantity,
		arg.NewQuantity,
		arg.Reason,
	)
	return err
}

const saveMakerPolicy = `-- name: SaveMakerPolicy :one
UPDATE public.products p SET made_to_order_fallback=$3,revision=p.revision+1
FROM public.owners o JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE p.shop_id=o.shop_id AND s.digest=$1 AND p.id=$2 AND p.revision=$4
AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
RETURNING p.id
`

type SaveMakerPolicyParams struct {
	Digest              []byte
	ID                  int64
	MadeToOrderFallback bool
	Revision            int64
}

func (q *Queries) SaveMakerPolicy(ctx context.Context, arg SaveMakerPolicyParams) (int64, error) {
	row := q.db.QueryRow(ctx, saveMakerPolicy,
		arg.Digest,
		arg.ID,
		arg.MadeToOrderFallback,
		arg.Revision,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const unpublishProduct = `-- name: UnpublishProduct :exec
DELETE FROM public.product_publications WHERE product_id=$1
`

func (q *Queries) UnpublishProduct(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, unpublishProduct, productID)
	return err
}

const updateMakerVariant = `-- name: UpdateMakerVariant :execrows
UPDATE public.product_variants SET label=$3,label_key=$4,size_label=$5,colour_pair=$6,price_pence=$7,supply_mode=$8,stock_quantity=$9 WHERE product_id=$1 AND id=$2
`

type UpdateMakerVariantParams struct {
	ProductID     int64
	ID            int64
	Label         string
	LabelKey      string
	SizeLabel     string
	ColourPair    string
	PricePence    pgtype.Int8
	SupplyMode    string
	StockQuantity int64
}

func (q *Queries) UpdateMakerVariant(ctx context.Context, arg UpdateMakerVariantParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMakerVariant,
		arg.ProductID,
		arg.ID,
		arg.Label,
		arg.LabelKey,
		arg.SizeLabel,
		arg.ColourPair,
		arg.PricePence,
		arg.SupplyMode,
		arg.StockQuantity,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE public.products p SET name=$3,description=$4,price_pence=$5,certificate_name=$6,revision=p.revision+1
FROM public.owners o JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE p.shop_id=o.shop_id AND s.digest=$1 AND p.id=$2 AND p.revision=$7
AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
RETURNING p.id,p.name,p.description,p.price_pence,p.certificate_name,p.revision
`

type UpdateProductParams struct {
	Digest          []byte
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

type UpdateProductRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Digest,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PricePence,
		arg.CertificateName,
		arg.Revision,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePence,
		&i.CertificateName,
		&i.Revision,
	)
	return i, err
}
