// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogdb

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO public.products(shop_id,name,description,price_pence,certificate_name,creation_key,creation_hash)
SELECT o.shop_id,$2,$3,$4,$5,$6,$7 FROM public.owners o JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
RETURNING id,name,description,price_pence,certificate_name,revision
`

type CreateProductParams struct {
	Digest          []byte
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	CreationKey     string
	CreationHash    []byte
}

type CreateProductRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Digest,
		arg.Name,
		arg.Description,
		arg.PricePence,
		arg.CertificateName,
		arg.CreationKey,
		arg.CreationHash,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePence,
		&i.CertificateName,
		&i.Revision,
	)
	return i, err
}

const findCreation = `-- name: FindCreation :one
SELECT p.id,p.creation_hash FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id
WHERE o.id=$1 AND p.creation_key=$2
`

type FindCreationParams struct {
	ID          int64
	CreationKey string
}

type FindCreationRow struct {
	ID           int64
	CreationHash []byte
}

func (q *Queries) FindCreation(ctx context.Context, arg FindCreationParams) (FindCreationRow, error) {
	row := q.db.QueryRow(ctx, findCreation, arg.ID, arg.CreationKey)
	var i FindCreationRow
	err := row.Scan(&i.ID, &i.CreationHash)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT p.id,p.name,p.description,p.price_pence,p.certificate_name,p.revision
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
AND p.id>$2 ORDER BY p.id LIMIT 51
`

type ListProductsParams struct {
	Digest  []byte
	AfterID int64
}

type ListProductsRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Digest, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PricePence,
			&i.CertificateName,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readProduct = `-- name: ReadProduct :one
SELECT p.id,p.name,p.description,p.price_pence,p.certificate_name,p.revision
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadProductParams struct {
	Digest []byte
	ID     int64
}

type ReadProductRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) ReadProduct(ctx context.Context, arg ReadProductParams) (ReadProductRow, error) {
	row := q.db.QueryRow(ctx, readProduct, arg.Digest, arg.ID)
	var i ReadProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePence,
		&i.CertificateName,
		&i.Revision,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE public.products p SET name=$3,description=$4,price_pence=$5,certificate_name=$6,revision=p.revision+1
FROM public.owners o JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE p.shop_id=o.shop_id AND s.digest=$1 AND p.id=$2 AND p.revision=$7
AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
RETURNING p.id,p.name,p.description,p.price_pence,p.certificate_name,p.revision
`

type UpdateProductParams struct {
	Digest          []byte
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

type UpdateProductRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Digest,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PricePence,
		arg.CertificateName,
		arg.Revision,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePence,
		&i.CertificateName,
		&i.Revision,
	)
	return i, err
}
