// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMakerVariant = `-- name: AddMakerVariant :one
INSERT INTO public.product_variants(product_id,label,label_key,size_label,colour_pair,price_pence,supply_mode,stock_quantity)
VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id
`

type AddMakerVariantParams struct {
	ProductID     int64
	Label         string
	LabelKey      string
	SizeLabel     string
	ColourPair    string
	PricePence    pgtype.Int8
	SupplyMode    string
	StockQuantity int64
}

func (q *Queries) AddMakerVariant(ctx context.Context, arg AddMakerVariantParams) (int64, error) {
	row := q.db.QueryRow(ctx, addMakerVariant,
		arg.ProductID,
		arg.Label,
		arg.LabelKey,
		arg.SizeLabel,
		arg.ColourPair,
		arg.PricePence,
		arg.SupplyMode,
		arg.StockQuantity,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addPhoto = `-- name: AddPhoto :exec
INSERT INTO public.product_photos(id,product_id,content,media_type,alt,width,height) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type AddPhotoParams struct {
	ID        string
	ProductID int64
	Content   []byte
	MediaType string
	Alt       string
	Width     int32
	Height    int32
}

func (q *Queries) AddPhoto(ctx context.Context, arg AddPhotoParams) error {
	_, err := q.db.Exec(ctx, addPhoto,
		arg.ID,
		arg.ProductID,
		arg.Content,
		arg.MediaType,
		arg.Alt,
		arg.Width,
		arg.Height,
	)
	return err
}

const advancePublicationRevision = `-- name: AdvancePublicationRevision :one
UPDATE public.products p SET revision=p.revision+1
FROM public.owners o WHERE o.shop_id=p.shop_id AND o.id=$1 AND p.id=$2 AND p.revision=$3
RETURNING p.revision
`

type AdvancePublicationRevisionParams struct {
	ID       int64
	ID_2     int64
	Revision int64
}

func (q *Queries) AdvancePublicationRevision(ctx context.Context, arg AdvancePublicationRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, advancePublicationRevision, arg.ID, arg.ID_2, arg.Revision)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const createBasket = `-- name: CreateBasket :exec
INSERT INTO public.baskets(shop_id,digest)
SELECT shop_id,$2 FROM public.shop_publications WHERE public_key=$1
ON CONFLICT(shop_id,digest) DO NOTHING
`

type CreateBasketParams struct {
	PublicKey string
	Digest    []byte
}

func (q *Queries) CreateBasket(ctx context.Context, arg CreateBasketParams) error {
	_, err := q.db.Exec(ctx, createBasket, arg.PublicKey, arg.Digest)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO public.products(shop_id,name,description,price_pence,certificate_name,creation_key,creation_hash)
SELECT o.shop_id,$2,$3,$4,$5,$6,$7 FROM public.owners o JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
RETURNING id,name,description,price_pence,certificate_name,revision
`

type CreateProductParams struct {
	Digest          []byte
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	CreationKey     string
	CreationHash    []byte
}

type CreateProductRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Digest,
		arg.Name,
		arg.Description,
		arg.PricePence,
		arg.CertificateName,
		arg.CreationKey,
		arg.CreationHash,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePence,
		&i.CertificateName,
		&i.Revision,
	)
	return i, err
}

const deleteUnusedPhotos = `-- name: DeleteUnusedPhotos :exec
DELETE FROM public.product_photos f WHERE f.product_id=$1
AND NOT EXISTS(SELECT 1 FROM public.products p WHERE p.photo_id=f.id)
AND NOT EXISTS(SELECT 1 FROM public.product_publications pp WHERE pp.photo_id=f.id)
`

func (q *Queries) DeleteUnusedPhotos(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, deleteUnusedPhotos, productID)
	return err
}

const findCreation = `-- name: FindCreation :one
SELECT p.id,p.creation_hash FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id
WHERE o.id=$1 AND p.creation_key=$2
`

type FindCreationParams struct {
	ID          int64
	CreationKey string
}

type FindCreationRow struct {
	ID           int64
	CreationHash []byte
}

func (q *Queries) FindCreation(ctx context.Context, arg FindCreationParams) (FindCreationRow, error) {
	row := q.db.QueryRow(ctx, findCreation, arg.ID, arg.CreationKey)
	var i FindCreationRow
	err := row.Scan(&i.ID, &i.CreationHash)
	return i, err
}

const listMakerVariants = `-- name: ListMakerVariants :many
SELECT v.id,v.label,v.size_label,v.colour_pair,v.price_pence,v.supply_mode,v.stock_quantity
FROM public.product_variants v JOIN public.products p ON p.id=v.product_id JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
ORDER BY v.id LIMIT 51
`

type ListMakerVariantsParams struct {
	Digest []byte
	ID     int64
}

type ListMakerVariantsRow struct {
	ID            int64
	Label         string
	SizeLabel     string
	ColourPair    string
	PricePence    pgtype.Int8
	SupplyMode    string
	StockQuantity int64
}

func (q *Queries) ListMakerVariants(ctx context.Context, arg ListMakerVariantsParams) ([]ListMakerVariantsRow, error) {
	rows, err := q.db.Query(ctx, listMakerVariants, arg.Digest, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMakerVariantsRow
	for rows.Next() {
		var i ListMakerVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.SizeLabel,
			&i.ColourPair,
			&i.PricePence,
			&i.SupplyMode,
			&i.StockQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id,p.name,p.description,p.price_pence,p.certificate_name,p.revision
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
AND p.id>$2 ORDER BY p.id LIMIT 51
`

type ListProductsParams struct {
	Digest  []byte
	AfterID int64
}

type ListProductsRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Digest, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PricePence,
			&i.CertificateName,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBasket = `-- name: LockBasket :one
SELECT b.revision,b.lines,b.shipping_choice FROM public.baskets b JOIN public.shop_publications sp ON sp.shop_id=b.shop_id
WHERE sp.public_key=$1 AND b.digest=$2 AND b.expires_at>clock_timestamp() FOR UPDATE OF b
`

type LockBasketParams struct {
	PublicKey string
	Digest    []byte
}

type LockBasketRow struct {
	Revision       int64
	Lines          []byte
	ShippingChoice []byte
}

func (q *Queries) LockBasket(ctx context.Context, arg LockBasketParams) (LockBasketRow, error) {
	row := q.db.QueryRow(ctx, lockBasket, arg.PublicKey, arg.Digest)
	var i LockBasketRow
	err := row.Scan(&i.Revision, &i.Lines, &i.ShippingChoice)
	return i, err
}

const publicPhotoContent = `-- name: PublicPhotoContent :one
SELECT f.content,f.media_type FROM public.product_photos f JOIN public.products p ON p.id=f.product_id JOIN public.product_publications pp ON pp.product_id=p.id AND pp.photo_id=f.id JOIN public.shop_publications sp ON sp.shop_id=p.shop_id
WHERE sp.public_key=$1 AND p.id=$2 AND f.id=$3
`

type PublicPhotoContentParams struct {
	PublicKey string
	ID        int64
	ID_2      string
}

type PublicPhotoContentRow struct {
	Content   []byte
	MediaType string
}

func (q *Queries) PublicPhotoContent(ctx context.Context, arg PublicPhotoContentParams) (PublicPhotoContentRow, error) {
	row := q.db.QueryRow(ctx, publicPhotoContent, arg.PublicKey, arg.ID, arg.ID_2)
	var i PublicPhotoContentRow
	err := row.Scan(&i.Content, &i.MediaType)
	return i, err
}

const publicProduct = `-- name: PublicProduct :one
SELECT pp.snapshot,p.made_to_order_fallback,p.preparation_days_min,p.preparation_days_max FROM public.product_publications pp JOIN public.products p ON p.id=pp.product_id JOIN public.shop_publications sp ON sp.shop_id=p.shop_id
WHERE sp.public_key=$1 AND p.id=$2
`

type PublicProductParams struct {
	PublicKey string
	ID        int64
}

type PublicProductRow struct {
	Snapshot            []byte
	MadeToOrderFallback bool
	PreparationDaysMin  int32
	PreparationDaysMax  int32
}

func (q *Queries) PublicProduct(ctx context.Context, arg PublicProductParams) (PublicProductRow, error) {
	row := q.db.QueryRow(ctx, publicProduct, arg.PublicKey, arg.ID)
	var i PublicProductRow
	err := row.Scan(
		&i.Snapshot,
		&i.MadeToOrderFallback,
		&i.PreparationDaysMin,
		&i.PreparationDaysMax,
	)
	return i, err
}

const publicProducts = `-- name: PublicProducts :many
SELECT pp.snapshot,p.id FROM public.product_publications pp JOIN public.products p ON p.id=pp.product_id JOIN public.shop_publications sp ON sp.shop_id=p.shop_id
WHERE sp.public_key=$1 AND p.id>$2 ORDER BY p.id LIMIT 51
`

type PublicProductsParams struct {
	PublicKey string
	AfterID   int64
}

type PublicProductsRow struct {
	Snapshot []byte
	ID       int64
}

func (q *Queries) PublicProducts(ctx context.Context, arg PublicProductsParams) ([]PublicProductsRow, error) {
	rows, err := q.db.Query(ctx, publicProducts, arg.PublicKey, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicProductsRow
	for rows.Next() {
		var i PublicProductsRow
		if err := rows.Scan(&i.Snapshot, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicShipping = `-- name: PublicShipping :one
SELECT sh.revision,sh.shipping_services FROM public.shops sh JOIN public.shop_publications sp ON sp.shop_id=sh.id WHERE sp.public_key=$1
`

type PublicShippingRow struct {
	Revision         int64
	ShippingServices []byte
}

func (q *Queries) PublicShipping(ctx context.Context, publicKey string) (PublicShippingRow, error) {
	row := q.db.QueryRow(ctx, publicShipping, publicKey)
	var i PublicShippingRow
	err := row.Scan(&i.Revision, &i.ShippingServices)
	return i, err
}

const publicShop = `-- name: PublicShop :one
SELECT sp.name,sp.tagline,sp.description FROM public.shop_publications sp
WHERE sp.public_key=$1 AND EXISTS(SELECT 1 FROM public.products p JOIN public.product_publications pp ON pp.product_id=p.id WHERE p.shop_id=sp.shop_id)
`

type PublicShopRow struct {
	Name        string
	Tagline     string
	Description string
}

func (q *Queries) PublicShop(ctx context.Context, publicKey string) (PublicShopRow, error) {
	row := q.db.QueryRow(ctx, publicShop, publicKey)
	var i PublicShopRow
	err := row.Scan(&i.Name, &i.Tagline, &i.Description)
	return i, err
}

const publicVariantStock = `-- name: PublicVariantStock :many
SELECT v.id,v.supply_mode,v.stock_quantity FROM public.product_variants v JOIN public.products p ON p.id=v.product_id JOIN public.product_publications pp ON pp.product_id=p.id JOIN public.shop_publications sp ON sp.shop_id=p.shop_id
WHERE sp.public_key=$1 AND p.id=$2 ORDER BY v.id LIMIT 51
`

type PublicVariantStockParams struct {
	PublicKey string
	ID        int64
}

type PublicVariantStockRow struct {
	ID            int64
	SupplyMode    string
	StockQuantity int64
}

func (q *Queries) PublicVariantStock(ctx context.Context, arg PublicVariantStockParams) ([]PublicVariantStockRow, error) {
	rows, err := q.db.Query(ctx, publicVariantStock, arg.PublicKey, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicVariantStockRow
	for rows.Next() {
		var i PublicVariantStockRow
		if err := rows.Scan(&i.ID, &i.SupplyMode, &i.StockQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishProduct = `-- name: PublishProduct :exec
INSERT INTO public.product_publications(product_id,revision,snapshot,photo_id) VALUES($1,$2,$3,$4)
ON CONFLICT(product_id) DO UPDATE SET revision=excluded.revision,snapshot=excluded.snapshot,photo_id=excluded.photo_id
`

type PublishProductParams struct {
	ProductID int64
	Revision  int64
	Snapshot  []byte
	PhotoID   pgtype.Text
}

func (q *Queries) PublishProduct(ctx context.Context, arg PublishProductParams) error {
	_, err := q.db.Exec(ctx, publishProduct,
		arg.ProductID,
		arg.Revision,
		arg.Snapshot,
		arg.PhotoID,
	)
	return err
}

const publishShop = `-- name: PublishShop :one
INSERT INTO public.shop_publications(shop_id,public_key,name,tagline,description)
SELECT sh.id,$2,sh.name,sh.tagline,sh.description FROM public.shops sh JOIN public.owners o ON o.shop_id=sh.id WHERE o.id=$1
ON CONFLICT(shop_id) DO UPDATE SET name=excluded.name,tagline=excluded.tagline,description=excluded.description
RETURNING public_key
`

type PublishShopParams struct {
	ID        int64
	PublicKey string
}

func (q *Queries) PublishShop(ctx context.Context, arg PublishShopParams) (string, error) {
	row := q.db.QueryRow(ctx, publishShop, arg.ID, arg.PublicKey)
	var public_key string
	err := row.Scan(&public_key)
	return public_key, err
}

const purgeExpiredBaskets = `-- name: PurgeExpiredBaskets :exec
DELETE FROM public.baskets WHERE (shop_id,digest) IN (
SELECT b.shop_id,b.digest FROM public.baskets b JOIN public.shop_publications sp ON sp.shop_id=b.shop_id
WHERE sp.public_key=$1 AND b.expires_at<=clock_timestamp() ORDER BY b.expires_at LIMIT 1000
)
`

func (q *Queries) PurgeExpiredBaskets(ctx context.Context, publicKey string) error {
	_, err := q.db.Exec(ctx, purgeExpiredBaskets, publicKey)
	return err
}

const readBasket = `-- name: ReadBasket :one
SELECT b.revision,b.lines,b.shipping_choice FROM public.baskets b JOIN public.shop_publications sp ON sp.shop_id=b.shop_id
WHERE sp.public_key=$1 AND b.digest=$2 AND b.expires_at>clock_timestamp()
`

type ReadBasketParams struct {
	PublicKey string
	Digest    []byte
}

type ReadBasketRow struct {
	Revision       int64
	Lines          []byte
	ShippingChoice []byte
}

func (q *Queries) ReadBasket(ctx context.Context, arg ReadBasketParams) (ReadBasketRow, error) {
	row := q.db.QueryRow(ctx, readBasket, arg.PublicKey, arg.Digest)
	var i ReadBasketRow
	err := row.Scan(&i.Revision, &i.Lines, &i.ShippingChoice)
	return i, err
}

const readMakerProduct = `-- name: ReadMakerProduct :one
SELECT p.id,p.name,p.price_pence,p.revision,p.made_to_order_fallback,p.preparation_days_min,p.preparation_days_max
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadMakerProductParams struct {
	Digest []byte
	ID     int64
}

type ReadMakerProductRow struct {
	ID                  int64
	Name                string
	PricePence          int64
	Revision            int64
	MadeToOrderFallback bool
	PreparationDaysMin  int32
	PreparationDaysMax  int32
}

func (q *Queries) ReadMakerProduct(ctx context.Context, arg ReadMakerProductParams) (ReadMakerProductRow, error) {
	row := q.db.QueryRow(ctx, readMakerProduct, arg.Digest, arg.ID)
	var i ReadMakerProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PricePence,
		&i.Revision,
		&i.MadeToOrderFallback,
		&i.PreparationDaysMin,
		&i.PreparationDaysMax,
	)
	return i, err
}

const readPhoto = `-- name: ReadPhoto :one
SELECT p.revision,COALESCE(f.id,'')::text AS photo_id,COALESCE(f.alt,'')::text AS alt,COALESCE(f.width,0)::integer AS width,COALESCE(f.height,0)::integer AS height
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
LEFT JOIN public.product_photos f ON f.id=p.photo_id AND f.product_id=p.id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadPhotoParams struct {
	Digest []byte
	ID     int64
}

type ReadPhotoRow struct {
	Revision int64
	PhotoID  string
	Alt      string
	Width    int32
	Height   int32
}

func (q *Queries) ReadPhoto(ctx context.Context, arg ReadPhotoParams) (ReadPhotoRow, error) {
	row := q.db.QueryRow(ctx, readPhoto, arg.Digest, arg.ID)
	var i ReadPhotoRow
	err := row.Scan(
		&i.Revision,
		&i.PhotoID,
		&i.Alt,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const readPrivatePhotoContent = `-- name: ReadPrivatePhotoContent :one
SELECT f.content,f.media_type FROM public.product_photos f JOIN public.products p ON p.id=f.product_id AND p.photo_id=f.id JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadPrivatePhotoContentParams struct {
	Digest []byte
	ID     int64
}

type ReadPrivatePhotoContentRow struct {
	Content   []byte
	MediaType string
}

func (q *Queries) ReadPrivatePhotoContent(ctx context.Context, arg ReadPrivatePhotoContentParams) (ReadPrivatePhotoContentRow, error) {
	row := q.db.QueryRow(ctx, readPrivatePhotoContent, arg.Digest, arg.ID)
	var i ReadPrivatePhotoContentRow
	err := row.Scan(&i.Content, &i.MediaType)
	return i, err
}

const readProduct = `-- name: ReadProduct :one
SELECT p.id,p.name,p.description,p.price_pence,p.certificate_name,p.revision
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadProductParams struct {
	Digest []byte
	ID     int64
}

type ReadProductRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) ReadProduct(ctx context.Context, arg ReadProductParams) (ReadProductRow, error) {
	row := q.db.QueryRow(ctx, readProduct, arg.Digest, arg.ID)
	var i ReadProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePence,
		&i.CertificateName,
		&i.Revision,
	)
	return i, err
}

const readPublication = `-- name: ReadPublication :one
SELECT p.revision,COALESCE(pp.revision,0)::bigint AS published_revision,COALESCE(sp.public_key,'')::text AS public_key,sh.name AS shop_name,sh.tagline AS shop_tagline,sh.description AS shop_description,sh.revision AS shop_revision
FROM public.products p JOIN public.owners o ON o.shop_id=p.shop_id JOIN public.owner_sessions s ON s.owner_id=o.id
JOIN public.shops sh ON sh.id=p.shop_id LEFT JOIN public.product_publications pp ON pp.product_id=p.id LEFT JOIN public.shop_publications sp ON sp.shop_id=p.shop_id
WHERE s.digest=$1 AND p.id=$2 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadPublicationParams struct {
	Digest []byte
	ID     int64
}

type ReadPublicationRow struct {
	Revision          int64
	PublishedRevision int64
	PublicKey         string
	ShopName          string
	ShopTagline       string
	ShopDescription   string
	ShopRevision      int64
}

func (q *Queries) ReadPublication(ctx context.Context, arg ReadPublicationParams) (ReadPublicationRow, error) {
	row := q.db.QueryRow(ctx, readPublication, arg.Digest, arg.ID)
	var i ReadPublicationRow
	err := row.Scan(
		&i.Revision,
		&i.PublishedRevision,
		&i.PublicKey,
		&i.ShopName,
		&i.ShopTagline,
		&i.ShopDescription,
		&i.ShopRevision,
	)
	return i, err
}

const recordStockAdjustment = `-- name: RecordStockAdjustment :exec
INSERT INTO public.stock_adjustments(variant_id,owner_id,previous_quantity,new_quantity,reason) VALUES($1,$2,$3,$4,$5)
`

type RecordStockAdjustmentParams struct {
	VariantID        int64
	OwnerID          int64
	PreviousQuantity int64
	NewQuantity      int64
	Reason           string
}

func (q *Queries) RecordStockAdjustment(ctx context.Context, arg RecordStockAdjustmentParams) error {
	_, err := q.db.Exec(ctx, recordStockAdjustment,
		arg.VariantID,
		arg.OwnerID,
		arg.PreviousQuantity,
		arg.NewQuantity,
		arg.Reason,
	)
	return err
}

const saveBasket = `-- name: SaveBasket :execrows
UPDATE public.baskets b SET lines=$3,revision=b.revision+1,shipping_choice=$5 FROM public.shop_publications sp
WHERE sp.shop_id=b.shop_id AND sp.public_key=$1 AND b.digest=$2 AND b.revision=$4 AND b.expires_at>clock_timestamp()
`

type SaveBasketParams struct {
	PublicKey      string
	Digest         []byte
	Lines          []byte
	Revision       int64
	ShippingChoice []byte
}

func (q *Queries) SaveBasket(ctx context.Context, arg SaveBasketParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveBasket,
		arg.PublicKey,
		arg.Digest,
		arg.Lines,
		arg.Revision,
		arg.ShippingChoice,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveMakerPolicy = `-- name: SaveMakerPolicy :one
UPDATE public.products p SET made_to_order_fallback=$3,revision=p.revision+1,preparation_days_min=COALESCE($5,p.preparation_days_min),preparation_days_max=COALESCE($6,p.preparation_days_max)
FROM public.owners o JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE p.shop_id=o.shop_id AND s.digest=$1 AND p.id=$2 AND p.revision=$4
AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
RETURNING p.id
`

type SaveMakerPolicyParams struct {
	Digest              []byte
	ID                  int64
	MadeToOrderFallback bool
	Revision            int64
	PreparationDaysMin  pgtype.Int4
	PreparationDaysMax  pgtype.Int4
}

func (q *Queries) SaveMakerPolicy(ctx context.Context, arg SaveMakerPolicyParams) (int64, error) {
	row := q.db.QueryRow(ctx, saveMakerPolicy,
		arg.Digest,
		arg.ID,
		arg.MadeToOrderFallback,
		arg.Revision,
		arg.PreparationDaysMin,
		arg.PreparationDaysMax,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const selectPhoto = `-- name: SelectPhoto :one
UPDATE public.products p SET photo_id=$1,revision=p.revision+1
FROM public.owners o WHERE o.shop_id=p.shop_id AND o.id=$2 AND p.id=$3 AND p.revision=$4
RETURNING p.revision
`

type SelectPhotoParams struct {
	PhotoID   pgtype.Text
	OwnerID   int64
	ProductID int64
	Revision  int64
}

func (q *Queries) SelectPhoto(ctx context.Context, arg SelectPhotoParams) (int64, error) {
	row := q.db.QueryRow(ctx, selectPhoto,
		arg.PhotoID,
		arg.OwnerID,
		arg.ProductID,
		arg.Revision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const unpublishProduct = `-- name: UnpublishProduct :exec
DELETE FROM public.product_publications WHERE product_id=$1
`

func (q *Queries) UnpublishProduct(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, unpublishProduct, productID)
	return err
}

const updateMakerVariant = `-- name: UpdateMakerVariant :execrows
UPDATE public.product_variants SET label=$3,label_key=$4,size_label=$5,colour_pair=$6,price_pence=$7,supply_mode=$8,stock_quantity=$9 WHERE product_id=$1 AND id=$2
`

type UpdateMakerVariantParams struct {
	ProductID     int64
	ID            int64
	Label         string
	LabelKey      string
	SizeLabel     string
	ColourPair    string
	PricePence    pgtype.Int8
	SupplyMode    string
	StockQuantity int64
}

func (q *Queries) UpdateMakerVariant(ctx context.Context, arg UpdateMakerVariantParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMakerVariant,
		arg.ProductID,
		arg.ID,
		arg.Label,
		arg.LabelKey,
		arg.SizeLabel,
		arg.ColourPair,
		arg.PricePence,
		arg.SupplyMode,
		arg.StockQuantity,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE public.products p SET name=$3,description=$4,price_pence=$5,certificate_name=$6,revision=p.revision+1
FROM public.owners o JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE p.shop_id=o.shop_id AND s.digest=$1 AND p.id=$2 AND p.revision=$7
AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
RETURNING p.id,p.name,p.description,p.price_pence,p.certificate_name,p.revision
`

type UpdateProductParams struct {
	Digest          []byte
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

type UpdateProductRow struct {
	ID              int64
	Name            string
	Description     string
	PricePence      int64
	CertificateName string
	Revision        int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Digest,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PricePence,
		arg.CertificateName,
		arg.Revision,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PricePence,
		&i.CertificateName,
		&i.Revision,
	)
	return i, err
}
