// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Owner struct {
	ID                         int64
	ShopID                     int64
	Email                      string
	PasswordHash               string
	MfaCiphertext              []byte
	MfaEnabled                 bool
	LastTotpCounter            int64
	AuthVersion                int64
	CreatedAt                  pgtype.Timestamptz
	MfaEnrollmentSessionDigest []byte
	MfaEnrollmentExpiresAt     pgtype.Timestamptz
}

type OwnerAuthLimit struct {
	Bucket      []byte
	WindowStart pgtype.Timestamptz
	Attempts    int32
}

type OwnerLoginChallenge struct {
	Digest      []byte
	OwnerID     int64
	AuthVersion int64
	Purpose     string
	ExpiresAt   pgtype.Timestamptz
	Attempts    int32
	ConsumedAt  pgtype.Timestamptz
}

type OwnerRecoveryCode struct {
	OwnerID int64
	Digest  []byte
}

type OwnerSession struct {
	Digest      []byte
	OwnerID     int64
	AuthVersion int64
	CreatedAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type Product struct {
	ID                  int64
	ShopID              int64
	Name                string
	Description         string
	PricePence          int64
	CertificateName     string
	Revision            int64
	CreationKey         string
	CreationHash        []byte
	MadeToOrderFallback bool
}

type ProductPublication struct {
	ProductID int64
	Revision  int64
	Snapshot  []byte
}

type ProductVariant struct {
	ID            int64
	ProductID     int64
	Label         string
	LabelKey      string
	SizeLabel     string
	ColourPair    string
	PricePence    pgtype.Int8
	SupplyMode    string
	StockQuantity int64
}

type Shop struct {
	ID           int64
	Name         string
	CurrencyCode string
	CountryCode  string
	Timezone     string
	CreatedAt    pgtype.Timestamptz
	Tagline      string
	Description  string
	ContactEmail string
	Revision     int64
}

type ShopPublication struct {
	ShopID      int64
	PublicKey   string
	Name        string
	Tagline     string
	Description string
}

type StockAdjustment struct {
	ID               int64
	VariantID        int64
	OwnerID          int64
	PreviousQuantity int64
	NewQuantity      int64
	Reason           string
	CreatedAt        pgtype.Timestamptz
}
