// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop.sql

package shopdb

import (
	"context"
)

const lockShopRevision = `-- name: LockShopRevision :one
SELECT shop.revision FROM public.shops shop JOIN public.owners owner ON owner.shop_id=shop.id WHERE owner.id=$1 FOR UPDATE OF shop
`

func (q *Queries) LockShopRevision(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockShopRevision, id)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const lockShopSession = `-- name: LockShopSession :one
SELECT owner.id FROM public.owners owner JOIN public.owner_sessions session ON session.owner_id=owner.id
WHERE session.digest=$1 AND session.auth_version=owner.auth_version
AND session.expires_at>clock_timestamp() AND session.last_seen_at>clock_timestamp()-interval '30 minutes'
FOR UPDATE OF owner,session
`

func (q *Queries) LockShopSession(ctx context.Context, digest []byte) (int64, error) {
	row := q.db.QueryRow(ctx, lockShopSession, digest)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const readShipping = `-- name: ReadShipping :one
SELECT sh.revision,sh.shipping_services FROM public.shops sh JOIN public.owners o ON o.shop_id=sh.id JOIN public.owner_sessions s ON s.owner_id=o.id
WHERE s.digest=$1 AND s.auth_version=o.auth_version AND s.expires_at>clock_timestamp() AND s.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadShippingRow struct {
	Revision         int64
	ShippingServices []byte
}

func (q *Queries) ReadShipping(ctx context.Context, digest []byte) (ReadShippingRow, error) {
	row := q.db.QueryRow(ctx, readShipping, digest)
	var i ReadShippingRow
	err := row.Scan(&i.Revision, &i.ShippingServices)
	return i, err
}

const readShop = `-- name: ReadShop :one
SELECT shop.name,shop.tagline,shop.description,shop.contact_email,shop.currency_code,shop.country_code,shop.timezone,shop.revision
FROM public.shops shop JOIN public.owners owner ON owner.shop_id=shop.id
JOIN public.owner_sessions session ON session.owner_id=owner.id
WHERE session.digest=$1 AND session.auth_version=owner.auth_version
AND session.expires_at>clock_timestamp() AND session.last_seen_at>clock_timestamp()-interval '30 minutes'
`

type ReadShopRow struct {
	Name         string
	Tagline      string
	Description  string
	ContactEmail string
	CurrencyCode string
	CountryCode  string
	Timezone     string
	Revision     int64
}

func (q *Queries) ReadShop(ctx context.Context, digest []byte) (ReadShopRow, error) {
	row := q.db.QueryRow(ctx, readShop, digest)
	var i ReadShopRow
	err := row.Scan(
		&i.Name,
		&i.Tagline,
		&i.Description,
		&i.ContactEmail,
		&i.CurrencyCode,
		&i.CountryCode,
		&i.Timezone,
		&i.Revision,
	)
	return i, err
}

const saveShipping = `-- name: SaveShipping :one
UPDATE public.shops sh SET shipping_services=$2,revision=sh.revision+1 FROM public.owners o
WHERE o.id=$1 AND o.shop_id=sh.id RETURNING sh.revision,sh.shipping_services
`

type SaveShippingParams struct {
	ID               int64
	ShippingServices []byte
}

type SaveShippingRow struct {
	Revision         int64
	ShippingServices []byte
}

func (q *Queries) SaveShipping(ctx context.Context, arg SaveShippingParams) (SaveShippingRow, error) {
	row := q.db.QueryRow(ctx, saveShipping, arg.ID, arg.ShippingServices)
	var i SaveShippingRow
	err := row.Scan(&i.Revision, &i.ShippingServices)
	return i, err
}

const saveShop = `-- name: SaveShop :one
UPDATE public.shops shop SET name=$2,tagline=$3,description=$4,contact_email=$5,revision=shop.revision+1
FROM public.owners owner JOIN public.owner_sessions session ON session.owner_id=owner.id
WHERE shop.id=owner.shop_id AND session.digest=$1 AND session.auth_version=owner.auth_version
AND session.expires_at>clock_timestamp() AND session.last_seen_at>clock_timestamp()-interval '30 minutes'
RETURNING shop.name,shop.tagline,shop.description,shop.contact_email,shop.currency_code,shop.country_code,shop.timezone,shop.revision
`

type SaveShopParams struct {
	Digest       []byte
	Name         string
	Tagline      string
	Description  string
	ContactEmail string
}

type SaveShopRow struct {
	Name         string
	Tagline      string
	Description  string
	ContactEmail string
	CurrencyCode string
	CountryCode  string
	Timezone     string
	Revision     int64
}

func (q *Queries) SaveShop(ctx context.Context, arg SaveShopParams) (SaveShopRow, error) {
	row := q.db.QueryRow(ctx, saveShop,
		arg.Digest,
		arg.Name,
		arg.Tagline,
		arg.Description,
		arg.ContactEmail,
	)
	var i SaveShopRow
	err := row.Scan(
		&i.Name,
		&i.Tagline,
		&i.Description,
		&i.ContactEmail,
		&i.CurrencyCode,
		&i.CountryCode,
		&i.Timezone,
		&i.Revision,
	)
	return i, err
}
